name: Tests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          key: npm-cache-${{ hashFiles('package-lock.json', 'package.json') }}
          path: node_modules

      - name: Cache Jest transforms
        uses: actions/cache@v3
        with:
          key: jest-cache
          path: .cache/jest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npx percy exec -- npm test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
